DEFINE
    VAR MinimumAmount = 2000000
    VAR MaximumAmount = 8000000
EVALUATE
FILTER (
    ADDCOLUMNS (
        SUMMARIZE (
            Sales,
            'Product'[Category]
        ),
        "Category Amount", [Sales Amount]
    ),
    AND (
        [Category Amount] >= MinimumAmount,
        [Category Amount] <= MaximumAmount
    )
)
ORDER BY [Category Amount]