DEFINE
    VAR MinimumAmount = 2000000
    VAR MaximumAmount = 8000000
    VAR CategoriesSales =
        ADDCOLUMNS (
            SUMMARIZE (
                sales,
                'Product'[Category]
            ),
            "Category Amount", [Sales Amount]
        )

EVALUATE
FILTER (
    CategoriesSales,
    AND (
        [Category Amount] >= MinimumAmount,
        [Category Amount] <= MaximumAmount
    )
)
ORDER BY [Category Amount]